package com.magic.api.commons.constants;

/**
 * PhoneCodeConstants
 *
 * @author zj
 * @date 2016/7/20
 */
public class PhoneCodeConstants {

    public static final String PHONE_CODE = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<regions>\n" +
            "    <region>\n" +
            "        <name>中国</name>\n" +
            "        <code>86</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>香港</name>\n" +
            "        <code>852</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>澳门</name>\n" +
            "        <code>853</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>美国</name>\n" +
            "        <code>1</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>加拿大</name>\n" +
            "        <code>1</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>埃及</name>\n" +
            "        <code>20</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>拟分配西撒哈拉</name>\n" +
            "        <code>210</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>南苏丹</name>\n" +
            "        <code>211</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>摩洛哥</name>\n" +
            "        <code>212</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>阿尔及利亚</name>\n" +
            "        <code>213</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>突尼斯</name>\n" +
            "        <code>216</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>利比亚</name>\n" +
            "        <code>218</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>冈比亚</name>\n" +
            "        <code>220</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>塞内加尔</name>\n" +
            "        <code>221</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>毛里塔尼亚</name>\n" +
            "        <code>222</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>马里</name>\n" +
            "        <code>223</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>几内亚</name>\n" +
            "        <code>224</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>象牙海岸</name>\n" +
            "        <code>225</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>布基纳法索</name>\n" +
            "        <code>226</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>尼日尔</name>\n" +
            "        <code>227</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>多哥</name>\n" +
            "        <code>228</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>贝宁</name>\n" +
            "        <code>229</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>毛里求斯</name>\n" +
            "        <code>230</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>利比里亚</name>\n" +
            "        <code>231</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>塞拉利昂</name>\n" +
            "        <code>232</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>加纳</name>\n" +
            "        <code>233</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>尼日利亚</name>\n" +
            "        <code>234</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>乍得</name>\n" +
            "        <code>235</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>中非共和国</name>\n" +
            "        <code>236</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>喀麦隆</name>\n" +
            "        <code>237</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>佛得角</name>\n" +
            "        <code>238</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>圣多美和普林西比</name>\n" +
            "        <code>239</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>赤道几内亚</name>\n" +
            "        <code>240</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>加蓬</name>\n" +
            "        <code>241</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>刚果共和国(布)</name>\n" +
            "        <code>242</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>刚果民主共和国(金)</name>\n" +
            "        <code>243</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>安哥拉</name>\n" +
            "        <code>244</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>几内亚比绍</name>\n" +
            "        <code>245</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>迪戈加西亚岛</name>\n" +
            "        <code>246</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>阿森松岛</name>\n" +
            "        <code>247</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>塞舌尔</name>\n" +
            "        <code>248</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>苏丹共和国|苏丹</name>\n" +
            "        <code>249</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>卢旺达</name>\n" +
            "        <code>250</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>埃塞俄比亚</name>\n" +
            "        <code>251</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>索马里</name>\n" +
            "        <code>252</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>吉布提</name>\n" +
            "        <code>253</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>肯尼亚</name>\n" +
            "        <code>254</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>坦桑尼亚</name>\n" +
            "        <code>255</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>乌干达</name>\n" +
            "        <code>256</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>布隆迪</name>\n" +
            "        <code>257</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>莫桑比克</name>\n" +
            "        <code>258</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>桑西巴</name>\n" +
            "        <code>259</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>赞比亚</name>\n" +
            "        <code>260</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>马达加斯加</name>\n" +
            "        <code>261</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>留尼汪和马约特</name>\n" +
            "        <code>262</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>津巴布韦</name>\n" +
            "        <code>263</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>纳米比亚</name>\n" +
            "        <code>264</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>马拉维</name>\n" +
            "        <code>265</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>莱索托</name>\n" +
            "        <code>266</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>博茨瓦纳</name>\n" +
            "        <code>267</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>斯威士兰</name>\n" +
            "        <code>268</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>科摩罗</name>\n" +
            "        <code>269</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>南非</name>\n" +
            "        <code>27</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>圣赫勒拿</name>\n" +
            "        <code>290</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>厄立特里亚</name>\n" +
            "        <code>291</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>阿鲁巴</name>\n" +
            "        <code>297</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>法罗群岛</name>\n" +
            "        <code>298</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>格陵兰</name>\n" +
            "        <code>299</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>希腊</name>\n" +
            "        <code>30</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>荷兰</name>\n" +
            "        <code>31</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>比利时</name>\n" +
            "        <code>32</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>法国</name>\n" +
            "        <code>33</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>西班牙</name>\n" +
            "        <code>34</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>直布罗陀</name>\n" +
            "        <code>350</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>葡萄牙</name>\n" +
            "        <code>351</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>卢森堡</name>\n" +
            "        <code>352</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>爱尔兰共和国|爱尔兰</name>\n" +
            "        <code>353</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>冰岛</name>\n" +
            "        <code>354</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>阿尔巴尼亚</name>\n" +
            "        <code>355</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>马耳他</name>\n" +
            "        <code>356</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>塞浦路斯</name>\n" +
            "        <code>357</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>芬兰</name>\n" +
            "        <code>358</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>保加利亚</name>\n" +
            "        <code>359</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>匈牙利</name>\n" +
            "        <code>36</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>立陶宛</name>\n" +
            "        <code>370</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>拉脱维亚</name>\n" +
            "        <code>371</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>爱沙尼亚</name>\n" +
            "        <code>372</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>摩尔多瓦</name>\n" +
            "        <code>373</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>亚美尼亚</name>\n" +
            "        <code>374</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>白俄罗斯</name>\n" +
            "        <code>375</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>安道尔</name>\n" +
            "        <code>376</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>摩纳哥</name>\n" +
            "        <code>377</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>圣马力诺</name>\n" +
            "        <code>378</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>保留给梵蒂冈</name>\n" +
            "        <code>379</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>乌克兰</name>\n" +
            "        <code>380</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>塞尔维亚</name>\n" +
            "        <code>381</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>蒙特內哥罗</name>\n" +
            "        <code>382</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>克罗地亚</name>\n" +
            "        <code>385</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>斯洛文尼亚</name>\n" +
            "        <code>386</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>波黑</name>\n" +
            "        <code>387</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>―环欧洲服务</name>\n" +
            "        <code>388</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>马其顿</name>\n" +
            "        <code>389</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>意大利</name>\n" +
            "        <code>39</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>罗马尼亚</name>\n" +
            "        <code>40</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>瑞士</name>\n" +
            "        <code>41</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>捷克</name>\n" +
            "        <code>420</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>斯洛伐克</name>\n" +
            "        <code>421</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>列支敦士登</name>\n" +
            "        <code>423</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>奥地利</name>\n" +
            "        <code>43</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>英国</name>\n" +
            "        <code>44</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>丹麦</name>\n" +
            "        <code>45</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>瑞典</name>\n" +
            "        <code>46</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>挪威</name>\n" +
            "        <code>47</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>波兰</name>\n" +
            "        <code>48</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>德国</name>\n" +
            "        <code>49</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>福克兰群岛</name>\n" +
            "        <code>500</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>伯利兹</name>\n" +
            "        <code>501</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>危地马拉</name>\n" +
            "        <code>502</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>萨尔瓦多</name>\n" +
            "        <code>503</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>洪都拉斯</name>\n" +
            "        <code>504</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>尼加拉瓜</name>\n" +
            "        <code>505</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>哥斯达黎加</name>\n" +
            "        <code>506</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>巴拿马</name>\n" +
            "        <code>507</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>圣皮埃尔和密克隆群岛</name>\n" +
            "        <code>508</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>海地</name>\n" +
            "        <code>509</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>秘鲁</name>\n" +
            "        <code>51</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>墨西哥</name>\n" +
            "        <code>52</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>古巴</name>\n" +
            "        <code>53</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>阿根廷</name>\n" +
            "        <code>54</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>巴西</name>\n" +
            "        <code>55</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>智利</name>\n" +
            "        <code>56</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>哥伦比亚</name>\n" +
            "        <code>57</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>委内瑞拉</name>\n" +
            "        <code>58</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>瓜德罗普</name>\n" +
            "        <code>590</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>玻利维亚</name>\n" +
            "        <code>591</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>圭亚那</name>\n" +
            "        <code>592</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>厄瓜多尔</name>\n" +
            "        <code>593</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>法属圭亚那</name>\n" +
            "        <code>594</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>巴拉圭</name>\n" +
            "        <code>595</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>马提尼克</name>\n" +
            "        <code>596</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>苏里南</name>\n" +
            "        <code>597</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>乌拉圭</name>\n" +
            "        <code>598</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>荷属安的列斯</name>\n" +
            "        <code>599</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>马来西亚</name>\n" +
            "        <code>60</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>澳大利亚</name>\n" +
            "        <code>61</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>印度尼西亚</name>\n" +
            "        <code>62</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>菲律宾</name>\n" +
            "        <code>63</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>新西兰</name>\n" +
            "        <code>64</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>新加坡</name>\n" +
            "        <code>65</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>泰国</name>\n" +
            "        <code>66</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>东帝汶</name>\n" +
            "        <code>670</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>文莱</name>\n" +
            "        <code>673</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>瑙鲁</name>\n" +
            "        <code>674</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>巴布亚新几内亚</name>\n" +
            "        <code>675</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>汤加</name>\n" +
            "        <code>676</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>所罗门群岛</name>\n" +
            "        <code>677</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>瓦努阿图</name>\n" +
            "        <code>678</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>斐济</name>\n" +
            "        <code>679</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>帕劳</name>\n" +
            "        <code>680</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>瓦利斯和富图纳群岛</name>\n" +
            "        <code>681</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>库克群岛</name>\n" +
            "        <code>682</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>纽埃</name>\n" +
            "        <code>683</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>美属萨摩亚</name>\n" +
            "        <code>684</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>萨摩亚</name>\n" +
            "        <code>685</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>基里巴斯,吉尔伯特群岛</name>\n" +
            "        <code>686</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>新喀里多尼亚</name>\n" +
            "        <code>687</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>图瓦卢,埃利斯群岛</name>\n" +
            "        <code>688</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>法属波利尼西亚</name>\n" +
            "        <code>689</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>托克劳群岛</name>\n" +
            "        <code>690</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>密克罗尼西亚联邦</name>\n" +
            "        <code>691</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>马绍尔群岛</name>\n" +
            "        <code>692</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>俄罗斯、哈萨克斯坦</name>\n" +
            "        <code>7</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>日本</name>\n" +
            "        <code>81</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>韩国</name>\n" +
            "        <code>82</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>越南</name>\n" +
            "        <code>84</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>朝鲜</name>\n" +
            "        <code>850</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>柬埔寨</name>\n" +
            "        <code>855</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>老挝</name>\n" +
            "        <code>856</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>环球个人通讯服务</name>\n" +
            "        <code>878</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>孟加拉人民共和国</name>\n" +
            "        <code>880</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>国际网络</name>\n" +
            "        <code>882</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>台湾</name>\n" +
            "        <code>886</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>土耳其</name>\n" +
            "        <code>90</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>印度</name>\n" +
            "        <code>91</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>巴基斯坦</name>\n" +
            "        <code>92</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>阿富汗</name>\n" +
            "        <code>93</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>斯里兰卡</name>\n" +
            "        <code>94</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>缅甸</name>\n" +
            "        <code>95</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>马尔代夫</name>\n" +
            "        <code>960</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>黎巴嫩</name>\n" +
            "        <code>961</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>约旦</name>\n" +
            "        <code>962</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>叙利亚</name>\n" +
            "        <code>963</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>伊拉克</name>\n" +
            "        <code>964</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>科威特</name>\n" +
            "        <code>965</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>沙特阿拉伯</name>\n" +
            "        <code>966</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>也门</name>\n" +
            "        <code>967</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>阿曼</name>\n" +
            "        <code>968</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>巴勒斯坦</name>\n" +
            "        <code>970</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>阿拉伯联合酋长国</name>\n" +
            "        <code>971</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>以色列</name>\n" +
            "        <code>972</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>巴林</name>\n" +
            "        <code>973</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>卡塔尔</name>\n" +
            "        <code>974</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>不丹</name>\n" +
            "        <code>975</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>蒙古</name>\n" +
            "        <code>976</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>尼泊尔</name>\n" +
            "        <code>977</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>伊朗</name>\n" +
            "        <code>98</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>塔吉克斯坦</name>\n" +
            "        <code>992</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>土库曼斯坦</name>\n" +
            "        <code>993</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>阿塞拜疆</name>\n" +
            "        <code>994</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>格鲁吉亚</name>\n" +
            "        <code>995</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>吉尔吉斯斯坦</name>\n" +
            "        <code>996</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>乌兹别克斯坦</name>\n" +
            "        <code>998</code>\n" +
            "    </region>\n" +
            "    <region>\n" +
            "        <name>紧急救援</name>\n" +
            "        <code>999</code>\n" +
            "    </region>\n" +
            "</regions>";

}
