/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.magic.config.thrift.base;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum CmdType implements TEnum {
  PASSPORT(16),
  PAYMENT(32),
  SETTLE(48),
  QUERY(64),
  CONFIG(80),
  GAME(96),
  BETRECORD(112);

  private final int value;

  private CmdType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CmdType findByValue(int value) { 
    switch (value) {
      case 16:
        return PASSPORT;
      case 32:
        return PAYMENT;
      case 48:
        return SETTLE;
      case 64:
        return QUERY;
      case 80:
        return CONFIG;
      case 96:
        return GAME;
      case 112:
        return BETRECORD;
      default:
        return null;
    }
  }
}
